import { Router, type IRouter } from "express";
import { eq, desc, sql } from "drizzle-orm";
import { db, conversationsTable, messagesTable, summariesTable, settingsTable } from "@workspace/db";
import {
  GetConversationParams,
  GetConversationMessagesParams,
  SummarizeConversationParams,
  CreateMessageBody,
  ListConversationsResponse,
  GetConversationResponse,
  GetConversationMessagesResponse,
  SummarizeConversationResponse,
  GetDashboardStatsResponse,
  ListSummariesResponse,
  GetSettingsResponse,
  UpdateSettingsBody,
  UpdateSettingsResponse,
} from "@workspace/api-zod";

const router: IRouter = Router();

router.get("/conversations", async (_req, res): Promise<void> => {
  const conversations = await db
    .select()
    .from(conversationsTable)
    .orderBy(desc(conversationsTable.lastMessageAt));

  const result = conversations.map((c) => ({
    ...c,
    hasSummary: c.hasSummary === "true",
    lastMessage: c.lastMessage ?? null,
    lastMessageAt: c.lastMessageAt?.toISOString() ?? null,
    createdAt: c.createdAt.toISOString(),
    updatedAt: c.updatedAt.toISOString(),
  }));

  res.json(ListConversationsResponse.parse(result));
});

router.get("/conversations/:id", async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const params = GetConversationParams.safeParse({ id: parseInt(raw, 10) });
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }

  const [conv] = await db
    .select()
    .from(conversationsTable)
    .where(eq(conversationsTable.id, params.data.id));

  if (!conv) {
    res.status(404).json({ error: "Conversation not found" });
    return;
  }

  res.json(
    GetConversationResponse.parse({
      ...conv,
      hasSummary: conv.hasSummary === "true",
      lastMessage: conv.lastMessage ?? null,
      lastMessageAt: conv.lastMessageAt?.toISOString() ?? null,
      createdAt: conv.createdAt.toISOString(),
      updatedAt: conv.updatedAt.toISOString(),
    })
  );
});

router.get("/conversations/:id/messages", async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const params = GetConversationMessagesParams.safeParse({ id: parseInt(raw, 10) });
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }

  const msgs = await db
    .select()
    .from(messagesTable)
    .where(eq(messagesTable.conversationId, params.data.id))
    .orderBy(messagesTable.timestamp);

  const result = msgs.map((m) => ({
    ...m,
    timestamp: m.timestamp.toISOString(),
    createdAt: m.createdAt.toISOString(),
  }));

  res.json(GetConversationMessagesResponse.parse(result));
});

router.post("/conversations/:id/summarize", async (req, res): Promise<void> => {
  const raw = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const params = SummarizeConversationParams.safeParse({ id: parseInt(raw, 10) });
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }

  const [conv] = await db
    .select()
    .from(conversationsTable)
    .where(eq(conversationsTable.id, params.data.id));

  if (!conv) {
    res.status(404).json({ error: "Conversation not found" });
    return;
  }

  const msgs = await db
    .select()
    .from(messagesTable)
    .where(eq(messagesTable.conversationId, params.data.id))
    .orderBy(messagesTable.timestamp);

  const [settings] = await db.select().from(settingsTable).limit(1);
  const summarizerUrl = settings?.summarizerWebhookUrl;

  let summaryContent = "";

  if (summarizerUrl) {
    try {
      const chatHistory = msgs.map((m) => `${m.role === "user" ? "Customer" : "AI"}: ${m.content}`).join("\n");
      const response = await fetch(summarizerUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          conversationId: params.data.id,
          contactName: conv.contactName,
          contactPhone: conv.contactPhone,
          messages: chatHistory,
        }),
      });

      if (response.ok) {
        const data = await response.json() as { summary?: string; output?: string };
        summaryContent = data.summary ?? data.output ?? "Summary generated by n8n workflow.";
      } else {
        summaryContent = `[n8n workflow returned ${response.status}] Auto-generated summary: ${msgs.length} messages exchanged between customer ${conv.contactName} and the AI assistant.`;
      }
    } catch {
      summaryContent = `Auto-generated summary: ${msgs.length} messages exchanged with ${conv.contactName} (${conv.contactPhone}).`;
    }
  } else {
    const userMsgs = msgs.filter((m) => m.role === "user");
    summaryContent = `Conversation summary for ${conv.contactName} (${conv.contactPhone}): ${msgs.length} total messages (${userMsgs.length} from customer). Configure the n8n summarizer webhook URL in Settings to use AI-powered summaries.`;
  }

  const [summary] = await db
    .insert(summariesTable)
    .values({ conversationId: params.data.id, content: summaryContent })
    .returning();

  await db
    .update(conversationsTable)
    .set({ hasSummary: "true" })
    .where(eq(conversationsTable.id, params.data.id));

  res.json(
    SummarizeConversationResponse.parse({
      summary: {
        ...summary,
        createdAt: summary.createdAt.toISOString(),
      },
      message: "Summary created successfully",
    })
  );
});

router.post("/messages", async (req, res): Promise<void> => {
  const parsed = CreateMessageBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  const { contactPhone, contactName, role, content, timestamp } = parsed.data;

  let [conv] = await db
    .select()
    .from(conversationsTable)
    .where(eq(conversationsTable.contactPhone, contactPhone));

  if (!conv) {
    const [newConv] = await db
      .insert(conversationsTable)
      .values({
        contactPhone,
        contactName: contactName ?? contactPhone,
        lastMessage: content,
        lastMessageAt: timestamp ? new Date(timestamp) : new Date(),
        messageCount: 0,
        hasSummary: "false",
      })
      .returning();
    conv = newConv;
  }

  const msgTimestamp = timestamp ? new Date(timestamp) : new Date();

  const [msg] = await db
    .insert(messagesTable)
    .values({
      conversationId: conv.id,
      role,
      content,
      timestamp: msgTimestamp,
    })
    .returning();

  await db
    .update(conversationsTable)
    .set({
      lastMessage: content,
      lastMessageAt: msgTimestamp,
      messageCount: sql`${conversationsTable.messageCount} + 1`,
    })
    .where(eq(conversationsTable.id, conv.id));

  res.status(201).json({
    ...msg,
    timestamp: msg.timestamp.toISOString(),
    createdAt: msg.createdAt.toISOString(),
  });
});

router.get("/summaries", async (_req, res): Promise<void> => {
  const summaries = await db
    .select()
    .from(summariesTable)
    .orderBy(desc(summariesTable.createdAt));

  const result = summaries.map((s) => ({
    ...s,
    createdAt: s.createdAt.toISOString(),
  }));

  res.json(ListSummariesResponse.parse(result));
});

router.get("/settings", async (_req, res): Promise<void> => {
  let [settings] = await db.select().from(settingsTable).limit(1);

  if (!settings) {
    const [newSettings] = await db
      .insert(settingsTable)
      .values({ chatbotWebhookUrl: null, summarizerWebhookUrl: null })
      .returning();
    settings = newSettings;
  }

  res.json(
    GetSettingsResponse.parse({
      ...settings,
      updatedAt: settings.updatedAt.toISOString(),
    })
  );
});

router.put("/settings", async (req, res): Promise<void> => {
  const parsed = UpdateSettingsBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  let [settings] = await db.select().from(settingsTable).limit(1);

  if (!settings) {
    const [newSettings] = await db
      .insert(settingsTable)
      .values({
        chatbotWebhookUrl: parsed.data.chatbotWebhookUrl ?? null,
        summarizerWebhookUrl: parsed.data.summarizerWebhookUrl ?? null,
      })
      .returning();
    settings = newSettings;
  } else {
    const [updated] = await db
      .update(settingsTable)
      .set({
        chatbotWebhookUrl: parsed.data.chatbotWebhookUrl ?? null,
        summarizerWebhookUrl: parsed.data.summarizerWebhookUrl ?? null,
      })
      .where(eq(settingsTable.id, settings.id))
      .returning();
    settings = updated;
  }

  res.json(
    UpdateSettingsResponse.parse({
      ...settings,
      updatedAt: settings.updatedAt.toISOString(),
    })
  );
});

router.get("/stats", async (_req, res): Promise<void> => {
  const [{ totalConversations }] = await db
    .select({ totalConversations: sql<number>`count(*)::int` })
    .from(conversationsTable);

  const [{ totalMessages }] = await db
    .select({ totalMessages: sql<number>`count(*)::int` })
    .from(messagesTable);

  const [{ totalSummaries }] = await db
    .select({ totalSummaries: sql<number>`count(*)::int` })
    .from(summariesTable);

  const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const [{ messagesLast24h }] = await db
    .select({ messagesLast24h: sql<number>`count(*)::int` })
    .from(messagesTable)
    .where(sql`${messagesTable.timestamp} >= ${oneDayAgo}`);

  const [{ activeConversations }] = await db
    .select({ activeConversations: sql<number>`count(*)::int` })
    .from(conversationsTable)
    .where(sql`${conversationsTable.lastMessageAt} >= ${oneDayAgo}`);

  res.json(
    GetDashboardStatsResponse.parse({
      totalConversations,
      totalMessages,
      totalSummaries,
      messagesLast24h,
      activeConversations,
    })
  );
});

export default router;
